import { Request, Response } from "express";
import { prisma } from "../../../../db/db";

// functionalities to be included for the admins of the groups
// ADD A MEMBER ACCORDING TO THEIR CHOICE
// REMOVE A MEMBER ACCORDING TO THEIR CHOICE
// MAKE THE GROUP ADMINS ONLY OR EVERYONE CAN SEND TEXTS
// MAKE THE GROUP OPEN TO ALL OR INVITE ONLY
// IF THERE IS ONLY ONE ADMIN, MAKE ANOTHER ONE ADMIN BEFORE EXITING: DONE
// DELETE A TEXT OF A MEMBER IN THE GROUP IF THE TEXT IS OFFENSIVE
// WHETHER THE GROUP SETTINGS CAN BE CHANGED BY ANY MEMBER OR BY THEM ONLY